const actionNames = Object.freeze({
    // User - Sign In
    USER_SIGNUP_START: 'USER_SIGNUP_START',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',

    //user - Sign Up
    USER_SIGNIN_START: 'USER_SIGNIN_START',
    USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
    USER_SIGNIN_FAIL: 'USER_SIGNIN_FAIL',

    // Remove error message
    REMOVE_SIGNUP_MESSAGE: 'REMOVE_SIGNUP_MESSAGE',
    REMOVE_SIGNIN_MESSAGE: 'REMOVE_SIGNIN_MESSAGE',

    //user - Sign Out
    USER_SIGNOUT: 'USER_SIGNOUT',

    // Library
    CREATE_LIBRARY_START: "CREATE_LIBRARY_START",
    CREATE_LIBRARY_SUCCESS: "CREATE_LIBRARY_SUCCESS",
    CREATE_LIBRARY_FAILED: "CREATE_LIBRARY_FAILED",
});

export default actionNames;
